export const roles = [
  { value: 'STUDENT', label: 'Student', description: 'Find mentors and opportunities' },
  { value: 'ALUMNI', label: 'Alumni', description: 'Offer mentorship and career advice' },
] as const;

export const capabilities = [
  { value: 'ORGANIZER', label: 'Organizer', description: 'Host and manage events' },
  { value: 'MENTOR', label: 'Mentor', description: 'Guide students through matching' },
  { value: 'RECRUITER', label: 'Recruiter', description: 'Share opportunities and hiring programs' },
  { value: 'MODERATOR', label: 'Moderator', description: 'Help keep the community healthy' },
  { value: 'ADMIN', label: 'Admin', description: 'Platform team operations' },
] as const;

export const domains = [
  'frontend',
  'backend',
  'full-stack',
  'mobile',
  'web3',
  'devops',
  'cloud',
  'cybersecurity',
  'ethical-hacking',
  'ctf',
  'ml',
  'data-science',
  'data-engineering',
  'iot',
  'embedded-systems',
  'robotics',
  'ar-vr',
  'game-development',
  'ui-ux',
  'product-management',
  'open-source',
  'competitive-programming',
  'database',
  'qa-testing',
] as const;

export const skillsOptions = [
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Vue',
  'Angular',
  'Tailwind CSS',
  'Node.js',
  'Express',
  'NestJS',
  'Django',
  'Flask',
  'FastAPI',
  'Spring Boot',
  'Java',
  'Python',
  'C',
  'C++',
  'C#',
  'Go',
  'Rust',
  'PHP',
  'Ruby',
  'Kotlin',
  'Swift',
  'Dart',
  'Flutter',
  'React Native',
  'Android',
  'iOS',
  'SQL',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'Prisma',
  'GraphQL',
  'REST APIs',
  'Docker',
  'Kubernetes',
  'Linux',
  'Git',
  'GitHub Actions',
  'AWS',
  'Azure',
  'Google Cloud',
  'Firebase',
  'Supabase',
  'Terraform',
  'CI/CD',
  'Machine Learning',
  'Deep Learning',
  'NLP',
  'Computer Vision',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Data Visualization',
  'Power BI',
  'Tableau',
  'Cybersecurity',
  'Network Security',
  'Web Security',
  'Reverse Engineering',
  'Cryptography',
  'Digital Forensics',
  'Blockchain',
  'Solidity',
  'Smart Contracts',
  'Figma',
  'UI Design',
  'UX Research',
  'Product Management',
  'Technical Writing',
  'Public Speaking',
] as const;

export const colleges = [
  'GBPIET Pauri',
  'IIT Delhi',
  'IIT Bombay',
  'IIT Madras',
  'IIT Kanpur',
  'BITS Pilani',
  'VIT Vellore',
  'Delhi Technological University',
  'NSUT Delhi',
  'Manipal Institute of Technology',
  'Other',
] as const;

export type CampusRole = (typeof roles)[number]['value'];
export type CampusCapability = (typeof capabilities)[number]['value'];
